# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

from sqlalchemy import Column, String, DateTime, text, Index

from server.database.relational_db.models import Base


class User(Base):
    __tablename__ = "user"

    # Primary key - UUID as string, generated by application
    id = Column(String(36), primary_key=True)

    # Required fields
    username = Column(String(360), nullable=False)
    password = Column(String(360), nullable=False)
    domain = Column(String(360), nullable=False)
    role = Column(String(200), nullable=False)

    # Timestamp fields - auto-generated in database
    created_at = Column(DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP"))
    updated_at = Column(
        DateTime, nullable=True, server_default=text("CURRENT_TIMESTAMP"), onupdate=text("CURRENT_TIMESTAMP")
    )

    # Soft delete field
    deleted_at = Column(DateTime, nullable=True)

    # Indexes
    __table_args__ = (Index("idx_user_deleted_at", "deleted_at"),)

    def __repr__(self):
        return f"<User(id='{self.id}', username='{self.username}', domain='{self.domain}', role='{self.role}')>"
